// Shared i18n copy for Oprova landing
window.OPROVA_COPY = {
  en: {
    nav: { how: "How", why: "Why" },
    hero: {
      eyebrow: "AX for teams without engineers",
      line1: "Your company,",
      line2: "run by agents.",
      sub: "We build and operate custom AI agents for small and mid-sized businesses — so you can transform without standing up an engineering team.",
      cta: "Get in touch",
      cta2: "See agents in action",
    },
    problem: {
      eyebrow: "The gap",
      title: "Everyone talks about AX.\nFew companies actually get there.",
      p1: "You don't have a dev team.",
      p2: "You can't out-hire Google for AI engineers.",
      p3: "The AI tools you already paid for? Mostly unused.",
      close: "Transformation shouldn't start with a platform team.",
    },
    who: {
      eyebrow: "Who it's for",
      title: "Operators who'd rather\nwork with agents than manage people.",
      items: [
        { k: "Retail & e-commerce", v: "Orders, support, inventory, vendor back-and-forth." },
        { k: "Clinics & services", v: "Intake, scheduling, follow-ups, billing." },
        { k: "Agencies & studios", v: "Briefs, reporting, QA, client threads." },
        { k: "Local manufacturers", v: "RFQs, production logs, supplier chasing." },
      ],
    },
    how: {
      eyebrow: "How it works",
      title: "Four weeks, roughly,\nfrom people-run to agent-run.",
      steps: [
        { n: "01", t: "Diagnose", d: "Two days on-site. We sit with your team and map the repeat tasks, handoffs, and decisions that eat the most hours." },
        { n: "02", t: "Design", d: "We pick the three to five agents that actually move the needle and write a job description for each one." },
        { n: "03", t: "Build", d: "We build on the tools you already use — inbox, sheets, your CRM, your ERP. Your team doesn't learn a new stack." },
        { n: "04", t: "Operate", d: "We stay on after launch. Monitoring, tuning, adding agents as the business changes. You never touch the code." },
      ],
    },
    core: {
      eyebrow: "Agents talking to agents",
      title: "Your agents handle it\nwith their agents.",
      caption: "A real low-grind problem — a late supplier shipment — worked out between agents. No human on the thread. Ops finds out after it's already resolved.",
      scenario: "SCENARIO · Supplier shipment 2 days late → 4 SKUs at risk → 38 customer orders affected",
      log: [
        { t: "09:02", who: "ops.oprova",       party: "you",      msg: "ERP flagged: SKU A••• shipment ETA slipped 48h. Pulling open orders…", kind: "think" },
        { t: "09:02", who: "ops.oprova",       party: "you",      msg: "38 orders at risk · escalating to supplier & fulfillment", kind: "act" },
        { t: "09:03", who: "ops.oprova",       party: "you",      msg: "@supplier.••• — can you confirm new ETA and partial split?", kind: "msg" },
        { t: "09:03", who: "supplier.•••",     party: "vendor",   msg: "Received. Checking line status.", kind: "in" },
        { t: "09:04", who: "supplier.•••",     party: "vendor",   msg: "New ETA 04/24 09:00. Can ship 60% on 04/22 if you accept split.", kind: "msg" },
        { t: "09:04", who: "ops.oprova",       party: "you",      msg: "Taking the 60% split. Reallocating by order priority…", kind: "act" },
        { t: "09:05", who: "ops.oprova",       party: "you",      msg: "@3pl.••• — book pickup 04/22 14:00, 60% of PO•••", kind: "msg" },
        { t: "09:05", who: "3pl.•••",          party: "partner",  msg: "Slot reserved. Confirming dock.", kind: "msg" },
        { t: "09:06", who: "ops.oprova",       party: "you",      msg: "@support.oprova — 22 customers need a heads-up (delay 2d)", kind: "msg" },
        { t: "09:06", who: "support.oprova",   party: "you",      msg: "22 replies drafted in KR/EN. Sending in batches of 5/min.", kind: "act" },
        { t: "09:08", who: "support.oprova",   party: "you",      msg: "3 customers want a refund → routing to @finance.oprova", kind: "msg" },
        { t: "09:08", who: "finance.oprova",   party: "you",      msg: "Refunds out · SLA credit applied · ledger updated", kind: "act" },
        { t: "09:09", who: "ops.oprova",       party: "you",      msg: "Closed. Human notified. No action needed.", kind: "done" },
      ],
      parties: [
        { id: "you",     label: "YOUR AGENTS",     sub: "ops · support · finance" },
        { id: "vendor",  label: "SUPPLIER AGENT",  sub: "partner ••• · masked" },
        { id: "partner", label: "3PL AGENT",       sub: "partner ••• · masked" },
      ],
    },
    metrics: {
      eyebrow: "Early signals",
      title: "From our first\nfew design partners.",
      items: [
        { big: "142", unit: "hrs / mo", label: "Operator hours handed back, per partner", foot: "Average across 5 partners, Feb–Apr 2026" },
        { big: "23", unit: "workflows", label: "Agent-run tasks in production", foot: "Support, ops, vendor, finance, scheduling" },
        { big: "4", unit: "weeks", label: "From kickoff to the first live agent", foot: "Median across partners" },
        { big: "0", unit: "engineers", label: "Needed on the customer side", foot: "We build it, we run it. You run the business." },
      ],
    },
    philosophy: {
      eyebrow: "Not this. This.",
      lines: ["Not software.", "Not automation.", "Not prompts.", "Agents, operated."],
    },
    cta: {
      eyebrow: "Design Partner Program",
      title: "Four partner slots\nleft this quarter.",
      sub: "A short note about your operation is enough. I'll write back with what I'd build first and whether a diagnostic week is worth your time — usually within a business day.",
      book: "mason@oprova.ai",
      mail: "Replies in EN or KO · Mason, founder",
    },
  },
  ko: {
    nav: { how: "도입", why: "왜" },
    hero: {
      eyebrow: "개발팀 없는 회사를 위한 AX",
      line1: "당신의 회사를,",
      line2: "에이전트가 운영합니다.",
      sub: "개발팀 없이 AX로 가고 싶은 중소기업을 위해, 필요한 에이전트를 직접 짓고 운영해드립니다.",
      cta: "문의하기",
      cta2: "에이전트 실행 보기",
    },
    problem: {
      eyebrow: "The gap",
      title: "다들 AX를 이야기하지만,\n실제로 도달하는 곳은 많지 않습니다.",
      p1: "개발팀이 없습니다.",
      p2: "구글과 경쟁해 AI 엔지니어를 뽑을 수 없습니다.",
      p3: "이미 결제해둔 AI 툴들은, 대부분 안 쓰입니다.",
      close: "전환의 조건이 '플랫폼 팀 먼저'여서는 안 됩니다.",
    },
    who: {
      eyebrow: "누구를 위한 것인가",
      title: "사람을 더 뽑기보다,\n에이전트와 일하고 싶은 운영자.",
      items: [
        { k: "리테일 · 이커머스", v: "주문, CS, 재고, 벤더 커뮤니케이션." },
        { k: "클리닉 · 서비스업", v: "접수, 예약, 사후관리, 정산." },
        { k: "에이전시 · 스튜디오", v: "브리프, 리포트, QA, 고객 스레드." },
        { k: "지역 제조", v: "견적, 생산 로그, 공급사 챙기기." },
      ],
    },
    how: {
      eyebrow: "도입 방식",
      title: "사람 운영에서 에이전트 운영까지,\n보통 4주 정도 걸립니다.",
      steps: [
        { n: "01", t: "진단", d: "이틀간 현장에 들어가 팀 시간을 가장 많이 잡아먹는 반복 업무, 핸드오프, 의사결정을 정리합니다." },
        { n: "02", t: "설계", d: "가장 레버리지가 큰 3~5개의 에이전트를 고르고, 각각 뭘 어디까지 할지 직무 기술서로 적어드립니다." },
        { n: "03", t: "구축", d: "이미 쓰고 있는 도구 위에 얹습니다 — 이메일, 시트, CRM, ERP. 팀이 새 스택을 배울 필요는 없습니다." },
        { n: "04", t: "운영", d: "구축 후에도 저희가 계속 운영합니다. 모니터링, 튜닝, 에이전트 추가까지. 코드를 직접 관리하실 일은 없습니다." },
      ],
    },
    core: {
      eyebrow: "에이전트끼리의 대화",
      title: "내 에이전트와 상대 에이전트가\n알아서 처리합니다.",
      caption: "공급사 배송 지연처럼 귀찮은 실무 이슈 하나. 스레드 위에는 사람이 없고, 운영팀은 이미 끝났다는 사실만 전달받습니다.",
      scenario: "시나리오 · 공급사 배송 2일 지연 → SKU 4개 위험 → 고객 주문 38건 영향",
      log: [
        { t: "09:02", who: "ops.oprova",     party: "you",     msg: "ERP 알림: SKU A••• ETA 48시간 밀림. 관련 주문 확인 중…", kind: "think" },
        { t: "09:02", who: "ops.oprova",     party: "you",     msg: "38건 영향 · 공급사·풀필먼트로 에스컬레이션", kind: "act" },
        { t: "09:03", who: "ops.oprova",     party: "you",     msg: "@supplier.••• — 새 ETA랑 분할 출고 가능한지 확인해줄래?", kind: "msg" },
        { t: "09:03", who: "supplier.•••",   party: "vendor",  msg: "수신. 라인 상태 체크 중.", kind: "in" },
        { t: "09:04", who: "supplier.•••",   party: "vendor",  msg: "새 ETA 04/24 09:00. 분할 수락하면 04/22에 60% 선출고 가능.", kind: "msg" },
        { t: "09:04", who: "ops.oprova",     party: "you",     msg: "60% 분할 수락. 주문 우선순위대로 재할당 중…", kind: "act" },
        { t: "09:05", who: "ops.oprova",     party: "you",     msg: "@3pl.••• — 04/22 14:00 픽업, PO••• 중 60%", kind: "msg" },
        { t: "09:05", who: "3pl.•••",        party: "partner", msg: "슬롯 예약 완료. 도크 확정할게요.", kind: "msg" },
        { t: "09:06", who: "ops.oprova",     party: "you",     msg: "@support.oprova — 고객 22명 먼저 안내 필요 (2일 지연)", kind: "msg" },
        { t: "09:06", who: "support.oprova", party: "you",     msg: "국/영문 22건 초안 작성. 분당 5건씩 발송합니다.", kind: "act" },
        { t: "09:08", who: "support.oprova", party: "you",     msg: "환불 요청 3건 → @finance.oprova로 넘김", kind: "msg" },
        { t: "09:08", who: "finance.oprova", party: "you",     msg: "환불 처리 · SLA 크레딧 적용 · 원장 업데이트", kind: "act" },
        { t: "09:09", who: "ops.oprova",     party: "you",     msg: "종결. 사람에게는 결과만 공유했습니다.", kind: "done" },
      ],
      parties: [
        { id: "you",     label: "내 에이전트",     sub: "ops · support · finance" },
        { id: "vendor",  label: "공급사 에이전트",  sub: "파트너 ••• · 비공개" },
        { id: "partner", label: "3PL 에이전트",     sub: "파트너 ••• · 비공개" },
      ],
    },
    metrics: {
      eyebrow: "초기 지표",
      title: "첫 파트너들에게서\n실제로 나온 숫자.",
      items: [
        { big: "142", unit: "시간/월", label: "파트너당 돌려받은 운영 시간", foot: "디자인 파트너 5곳 평균 · 2026.02–04" },
        { big: "23", unit: "워크플로우", label: "현장에서 돌고 있는 에이전트 업무", foot: "CS, 운영, 벤더, 재무, 예약" },
        { big: "4", unit: "주", label: "킥오프부터 첫 에이전트가 돌기까지", foot: "파트너 간 중위값" },
        { big: "0", unit: "엔지니어", label: "고객사에 필요한 엔지니어 수", foot: "저희가 짓고 운영합니다. 비즈니스는 당신이 하세요." },
      ],
    },
    philosophy: {
      eyebrow: "이게 아니라, 이겁니다.",
      lines: ["소프트웨어가 아닙니다.", "자동화도 아닙니다.", "프롬프트도 아닙니다.", "운영되는 에이전트입니다."],
    },
    cta: {
      eyebrow: "Design Partner Program",
      title: "이번 분기는\n네 팀 남았습니다.",
      sub: "운영에 대한 짧은 메모면 됩니다. 뭘 먼저 지을지, 진단 일주일이 시간 쓸 만한지에 대해 — 제가 직접 답장드려요. 보통 영업일 하루 안.",
      book: "mason@oprova.ai",
      mail: "한국어 / English 모두 가능 · Mason, 파운더",
    },
  },
};
